name: Deploy Private Angular Portfolio

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo (portfolio)
        uses: actions/checkout@v4
        with:
          repository: Dupy007/portfolio
          token: ${{ secrets.GH_TOKEN }}
          path: portfolio

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./portfolio

      - name: Build Angular project
        run: npm run build -- --configuration production
        working-directory: ./portfolio

      - name: Initialize Git in deployment folder
        working-directory: portfolio/dist/portfolio
        run: |
          cd portfolio/dist/portfolio
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: portfolio/dist/portfolio
          clean: true
